apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: driver-api
  template:
    metadata:
      labels:
        app: driver-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "driver-api"
        dapr.io/app-port: "5002"
    spec:
      containers:
      - name: driver-api
        image: driver-api:latest
        ports:
        - containerPort: 5002
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-api-service
spec:
  selector:
    app: driver-api
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP