apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "user-api"
        dapr.io/app-port: "5001"
    spec:
      containers:
      - name: user-api
        image: user-api:latest
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: KAFKA_BROKERS
          value: "kafka-service:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api
  ports:
  - port: 5001
    targetPort: 5001
  type: ClusterIP